before_script: bundle exec rake db:create db:schema:load
language: ruby

before_script:
  - psql -c 'create database status_test;' -U postgres
  - rake db:schema:load

rvm:
  - 1.9.3
  - 2.0.0
notifications:
  email:
  - sferik@gmail.com
  - evan+notify@phx.io
